### ISSUE TITLE
OpenCTi connector issue : __init__() takes from 3 to 5 positional arguments but 6 were given

### ISSUE THREAD

**Issue by IOTech17** [TheHive-Project/Cortex-Analyzers#994]
# OpenCTi connector issue : __init__() takes from 3 to 5 positional arguments but 6 were given

### Request Type
Bug

### Work Environment

Docker 20.10.6
Cortex 3.1.1

docker-compose : 

```
version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=hive
      - script.allowed_types=inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - bootstrap.memory_lock=true
      - gateway.recover_after_nodes=1
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - es_logs:/usr/share/elasticsearch/logs
    restart: always
  cassandra:
    container_name: cassandra
    image: cassandra:3.11
    restart: always
    hostname: cassandra
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=1G
      - CASSANDRA_CLUSTER_NAME=thp
    volumes:
      - cassandra_data:/var/lib/cassandra/data
  cortex:
    image: thehiveproject/cortex:3.1.1-1
    environment:
      - job_directory=/tmp/cortex-jobs
      - analyzer_urls=https://download.thehive-project.org/analyzers-devel.json
      - responder_urls=https://download.thehive-project.org/responders-devel.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/cortex-jobs:/tmp/cortex-jobs
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:10001:9001"
    command:
      --analyzer-url https://download.thehive-project.org/analyzers-devel.json
      --responder-url https://download.thehive-project.org/responders-devel.json
  thehive:
    container_name: thehive
    image: 'thehiveproject/thehive4:4.1.4-1'
    restart: always
    depends_on:
      - cassandra
    ports:
      - '0.0.0.0:10000:9000'
    volumes:
      - /docker/thehive4andcortex3_thehiveconf/application.conf:/etc/thehive/application.conf
      - thehive_data:/opt/thp/thehive/data
      - thehive_index:/opt/thp/thehive/index
    command:
      --cortex-port 9001
      --cortex-keys *hidden*
volumes:
  esdata:
  es_logs:
  cassandra_data:
  thehive_data:
  thehive_index:
```

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 20.04 docker host
| Cortex Analyzer Name      |  OpenCTI
| Cortex Analyzer Version   | 1.0
| Cortex Version            | 3.1.1

### Description
Describe your request as clearly as possible.

### Steps to Reproduce
Run a new analysis in cortex web UI
select opencti analyzer
analysis always endup with a failure and this error message : __init__() takes from 3 to 5 positional arguments but 6 were given
